from flask import session
from utils.db import Database  # uses your existing Mongo connection
from bson import ObjectId

def store_user_in_db(user_info):
    users = Database.get_collection("users")

    existing = users.find_one({"email": user_info.get("email")})
    if existing:
        return str(existing["_id"])  # ✅ use MongoDB’s actual _id

    result = users.insert_one(user_info)
    return str(result.inserted_id)  # ✅ this _id is generated by Mongo


def login_success_handler(provider, token, userinfo):
    user_data = {
        "provider": provider,
        "name": userinfo.get("name"),
        "email": userinfo.get("email"),
        "picture": userinfo.get("picture")
    }

    user_id = store_user_in_db(user_data)

    session["user"] = {
        **user_data,
        "_id": user_id  # ✅ ensure this is a plain string
    }

    return session["user"]

