version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5004:5004"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
